[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "genpatch"
version = "0.0.1"
description = "Generate locked fetchurl patches of nixpkgs prs"

[project.scripts]
genpatch = "genpatch.cli:main"
